# Generated by Django 4.1.4 on 2022-12-14 13:17

from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=django_resized.forms.ResizedImageField(crop=None, default='/home/theblindone/codeProjects/PythonProjects/puls_task/api/app/imgs/1.jpg', force_format='WEBP', keep_meta=True, quality=75, scale=None, size=[1920, 1080], upload_to='imgs/'),
        ),
    ]
